### ISSUE TITLE
Can't deploy with portainer

### ISSUE THREAD

**Issue by EnterTheMaelstrom** [gudarzi/SaveHere#49]
Hi there, 

when I try to use following docker-compose via portainer:
```
services:
 savehere:
   image: ghcr.io/gudarzi/savehere:latest
   environment:
     - ASPNETCORE_ENVIRONMENT=Production
     - ASPNETCORE_HTTP_PORTS=8080
     #- ASPNETCORE_HTTPS_PORTS=8081
     - SIGNALR_HUB_URL=http://localhost:8080/DownloadProgressHub
     - BASIC_AUTH_USERNAME="" # Provide Basic Auth Username If Required
     - BASIC_AUTH_PASSWORD="" # Provide Basic Auth Password If Required
     #- PUID=1000
     #- PGID=1000
     - "urls=http://0.0.0.0:8080"
   ports:
     - "172.17.0.1:18480:8080"
     #- "172.17.0.1:18481:8081"
   volumes:
     - /media/savehere/downloads:/app/downloads # Remove this if you experience very long loading times
     - /media/savehere/db:/app/db # Remove this if you experience very long loading times
   #user: 0:0
```
I get this deployment error message:
```
Failed to deploy a stack: savehere Pulling savehere Error Head "https://ghcr.io/v2/gudarzi/savehere/manifests/v3": unauthorized Error response from daemon: Head "https://ghcr.io/v2/gudarzi/savehere/manifests/v3": unauthorized
```

Do you know how I can solve this?
